services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
            target: frankenphp
        volumes:
            - ./:/app:delegated
        depends_on:
            db:
                condition: service_healthy
    db:
        image: mariadb
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - database:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: root_password
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            target: frontend
        volumes:
            - ./:/app
    mailhog:
        image: mailhog/mailhog:latest

volumes:
    database:
